[package]
name = 'LendConfig'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'a2a3bf79b68823287f962bded2abfaefc688e71c'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
lend_config='0xe0e07cb03df0d97f61a0ea236830f3bd6e1bfa3cf0bfdf592f11a7762d3d7909'